<?php

namespace AppBundle\Repository;

/**
 * NewsItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsItemRepository extends \Doctrine\ORM\EntityRepository
{
}
