<?php

namespace AppBundle\Repository;

/**
 * NewsSourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsSourceRepository extends \Doctrine\ORM\EntityRepository
{
}
